name: Build MSI (Windows)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-msi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install WiX Toolset 3.14.0
        run: choco install wixtoolset --version=3.14.0 -y --allow-downgrade --force
      - name: Install deps
        run: npm ci
      - name: Build MSI
        run: npx electron-builder --win msi
      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: GlobalCorp-Sim-MSI
          path: |
            dist\*.msi
            release\*.msi
